version: '3'
services:
  psql:
    image: postgres
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: workoutapp-pass
      POSTGRES_USER: postgres
      POSTGRES_DB: workoutapp
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ok-workoutapp-app-ktor:0.0.3
    container_name: app-ktor
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      SQL_URL: jdbc:postgresql://psql:5432/workoutapp
    depends_on:
      psql:
        condition: service_healthy

volumes:
  postgres_data: